concurrency:
  cancel-in-progress: true
  group: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  update:
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    steps:
    - env:
        SECRETS: "${{ toJSON(secrets) }}"
      name: "Secret tests"
      uses: "actions/github-script@v8"
      with:
        script: |
          const secrets = JSON.parse(process.env.SECRETS);
          if (secrets.GPG_KEY === undefined || secrets.RADXA_APT_KEY_2024 === undefined) {
              core.setFailed('Required secrets are unset!');
          }
    - name: "Checkout rsdk"
      uses: "actions/checkout@v6"
      with:
        ref: "40f9df085606563478ff1aa4f08d0759a81fc084"
        repository: "RadxaOS-SDK/rsdk"
    - name: "Checkout current repo"
      uses: "actions/checkout@v6"
      with:
        path: ".infra-repo"
        token: "${{secrets.GIT_PUSH_TOKEN}}"
    - env:
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      id: "build"
      name: "Update pkgs.json"
      run: |
        pushd .infra-repo
        if [[ "${{ github.repository }}" != *-test ]] && \
            wget "https://raw.githubusercontent.com/${{ github.repository }}-test/main/pkgs.lock" -O pkgs.lock.new; then
            mv pkgs.lock.new pkgs.lock
            git add pkgs.lock
        fi
        
        ../src/bin/rsdk infra-pkg-snapshot
        git add pkgs.json
        
        if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m "chore: update package snapshot"
        fi
        popd
      shell: "bash"
    - if: "github.event_name != 'pull_request'"
      name: "Commit package snapshot"
      run: |
        pushd .infra-repo
        git push
        popd
      shell: "bash"
name: "Update package version info"
"on":
  pull_request:
    paths:
    - ".github/workflows/update.yaml"
  repository_dispatch:
    types:
    - "new_package_release"
  workflow_dispatch: {}
permissions: {}